provides: [caliptra_ss_top]
schema_version: 2.4.0
requires:
  - uvmf_lib
  - mcu_top
  - css_mcu0_veer_el2_rtl_pkg
  - i3c-core
  - caliptra_top_tb_pkg
targets:
  tb:
    directories:
      - $COMPILE_ROOT/vip
      - /cad/tools/mentor/avery/2023.2/axixactor-2.1e.230314//src.axi.VCS
      - /cad/tools/mentor/avery/2023.2/axixactor-2.1e.230314//src.axi
      - /cad/tools/mentor/avery/2023.2/axixactor-2.1e.230314//checker/BP063-BU-01000-r0p1-00rel0/sva
      - /cad/tools/mentor/avery/2023.2/axixactor-2.1e.230314//testbench
      - /cad/tools/mentor/avery/2024.3/avery_sim
      - /cad/tools/mentor/avery/2024.3/avery_sim/src
      - /cad/tools/mentor/avery/2024.3/avery_sim/src.IEEE
      - /cad/tools/mentor/avery/2024.3/avery_pli
      - /cad/tools/mentor/avery/2024.3/i3cxactor/
      - /cad/tools/mentor/avery/2024.3/i3cxactor/src
      - /cad/tools/mentor/avery/2024.3/i3cxactor/src.i3c
      - /cad/tools/mentor/avery/2024.3/i3cxactor/src.VCS
      - /cad/tools/mentor/avery/2024.3/i3cxactor/src.i3c
      - /cad/tools/mentor/avery/2024.3/i3cxactor/testsuite.i3c/examples
      - /cad/tools/mentor/avery/2024.3/i3cxactor/testsuite.i3c/examples.uvm
      - /cad/tools/mentor/avery/2024.3/i3cxactor/testsuite.i3c/dut
      - /cad/tools/mentor/avery/2024.3/i3cxactor/testsuite.i3c/dut1_1
      - /cad/tools/mentor/avery/2024.3/i3cxactor/testsuite.i3c/dut_slave
      - /cad/tools/mentor/avery/2024.3/i3cxactor/testsuite.i3c/dut_master
      - /cad/tools/mentor/avery/2024.3/i3cxactor/testsuite.i3c/dut_master_stby
      - /cad/tools/mentor/avery/2024.3/i3cxactor/testsuite.i3c/internal
      - /cad/tools/mentor/avery/2024.3/i3cxactor/testsuite.i3c/dut_basic
      - /cad/tools/mentor/avery/2024.3/i3cxactor/testsuite.i3c/dut_hci2
      - /cad/tools/mentor/avery/2024.3/i3cxactor/testsuite.i3c/dut_hci1_2
      - /cad/tools/mentor/avery/2024.3/i3cxactor/testbench
    files:
      # - $COMPILE_ROOT/../../../../chipsalliance/caliptra-rtl/src/axi/rtl/caliptra_axi_sram.sv
      - /cad/tools/mentor/avery/2023.2/axixactor-2.1e.230314//src/avery_pkg.sv
      - /cad/tools/mentor/avery/2023.2/axixactor-2.1e.230314//src/avery_pkg_test.sv
      - /cad/tools/mentor/avery/2023.2/axixactor-2.1e.230314//src.axi/aaxi_pkg.sv
      - /cad/tools/mentor/avery/2023.2/axixactor-2.1e.230314//src.axi/aaxi_pkg_xactor.sv
      - /cad/tools/mentor/avery/2023.2/axixactor-2.1e.230314//src.axi/aaxi_class_pll.sv
      - /cad/tools/mentor/avery/2023.2/axixactor-2.1e.230314//src.axi/aaxi_pkg_test.sv
      - /cad/tools/mentor/avery/2023.2/axixactor-2.1e.230314//src.axi/aaxi_intf.sv
      - /cad/tools/mentor/avery/2024.3/avery_sim/src/avery_pkg.sv
      - /cad/tools/mentor/avery/2024.3/avery_sim/src/avery_pkg_test.sv
      - /cad/tools/mentor/avery/2024.3/i3cxactor/src/ai2c_pkg.sv
      - /cad/tools/mentor/avery/2024.3/i3cxactor/src.i3c/ai3c_pkg.sv
      - /cad/tools/mentor/avery/2024.3/i3cxactor/src/ai2c_intf.sv
      - $COMPILE_ROOT/testbench/ai3c_intf.sv
      - /cad/tools/mentor/avery/2024.3/i3cxactor/src.i3c/ai3c_intf.sv
      - $COMPILE_ROOT/testbench/tb_top_pkg.sv
      - $COMPILE_ROOT/testbench/axi_slv.sv
      - $COMPILE_ROOT/testbench/dasm.svi
      - $COMPILE_ROOT/testbench/aaxi4_interconnect.sv
      - $COMPILE_ROOT/testbench/caliptra_ss_top.sv
    tops: [caliptra_ss_top]
  sim:
    pre_exec: '$MSFT_SCRIPTS_DIR/run_test_makefile && echo "[PRE-EXEC] Copying ECC vector generator to ${pwd}" && cp $COMPILE_ROOT/../../third_party/caliptra-rtl/src/ecc/tb/ecc_secp384r1.exe . 
                && echo "[PRE-EXEC] Copying DOE vector generator to ${pwd}" && cp $COMPILE_ROOT/../../third_party/caliptra-rtl/src/doe/tb/doe_test_gen.py .
                && echo "[PRE-EXEC] Copying SHA256 wntz vector generator to ${pwd}" && cp $COMPILE_ROOT/../../third_party/caliptra-rtl/src/sha256/tb/sha256_wntz_test_gen.py .
                && echo "[PRE-EXEC] Copying MLDSA vector generator to ${pwd}" && cp $COMPILE_ROOT/../../third_party/caliptra-rtl/submodules/adams-bridge/src/mldsa_top/uvmf/Dilithium_ref/dilithium/ref/test/test_dilithium5 .
                && echo "[PRE-EXEC] Copying MLDSA debug vector generator to ${pwd}" && cp $COMPILE_ROOT/../../third_party/caliptra-rtl/submodules/adams-bridge/src/mldsa_top/uvmf/Dilithium_ref/dilithium/ref/test/test_dilithium5_debug .
                && echo "[PRE-EXEC] Copying mldsa directed vector to ${pwd}" && cp $COMPILE_ROOT/../../third_party/caliptra-rtl/src/mldsa/tb/smoke_test_mldsa_vector.hex .'
global:
  tool:
    vcs:
      default:
        - '-assert svaext'
        - '-sverilog -full64'
        # Used in caliptra_top_sva to find signals
        - +define+CPTRA_TB_TOP_NAME=caliptra_ss_top
        - +define+CPTRA_TOP_PATH=caliptra_ss_top.caliptra_top_dut
        - +define+MCU_RV_BUILD_AXI4
        - +define+MCU_RV_OPENSOURCE
        - +define+AVERY_VCS
        - +define+AVERY_CLOCK=5
        - +define+FOUR_OUTSTANDING
        - +define+AVERY_AXI_INTERCONNECT
        - +define+AAXI_MAX_DATA_WIDTH=64
        - +define+AAXI_MAX_ADDR_WIDTH=64
        - +define+AAXI_MAX_ID_WIDTH=5
        - +define+CALIPTRA_INTERNAL_UART
        - '-noinherit_timescale=1ns/1ps'
        - +define+AAXI_INTC_MASTER_CNT=5
        - +define+AAXI_INTC_SLAVE_CNT=5
        - +define+AI3C_LANE_NUM=1
        - '/cad/tools/mentor/avery/2.5c/avery_pli-2023_0609/lib.linux/libtb_vcs64.a'
        - '-P /cad/tools/mentor/avery/2.5c/avery_pli-2023_0609/tb_vcs64.tab'
      elab:
        #FIXME implicit-wire-no-fanin and port-connection-width-mismatch warnings from i3c-core
        - '+warn=noIWNF'
        - '+warn=noPCWM-W'
        - '/cad/tools/mentor/avery/2.5c/avery_pli-2023_0609/lib.linux/libtb_vcs64.a'
        - '-P /cad/tools/mentor/avery/2.5c/avery_pli-2023_0609/tb_vcs64.tab'
        #FIXME unique case violations in i3c-core
        - '-ignore unique_checks'
      sim:
        # Uncomment for debug prints
        #- +aaxi_dbg_name=all
        - '+vpi -lpthread'
