provides: [mci_pkg]
schema_version: 2.4.0
targets:
  rtl:
    directories: [$COMPILE_ROOT/rtl]
    files:
      - $COMPILE_ROOT/rtl/mci_pkg.sv
  tb:
    directories: [$COMPILE_ROOT/rtl]
    files:
      - $COMPILE_ROOT/rtl/mci_pkg.sv
---
provides: [mci_top]
schema_version: 2.4.0
requires:
  - caliptra_prim
  - axi_sub
  - soc_ifc_top
  - mci_pkg
targets:
  rtl:
    directories:
      - $COMPILE_ROOT/rtl
    files:
      - $COMPILE_ROOT/rtl/mci_boot_seqr.sv
      - $COMPILE_ROOT/rtl/mci_top.sv
    tops: [mci_top]
  rtl_lint:
    directories: [$COMPILE_ROOT/config/design_lint]
    waiver_files:
      - $MSFT_REPO_ROOT/src/mci/config/design_lint/mci/sglint_waivers
    tops: [mci_top]
